import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Sidebar from '@/components/Sidebar/Sidebar.component';
import Header from '@/components/Header/Header.component';
import SidebarContextProvider from '@/contexts/Sidebar/Sidebar.context';
import DeviceWidthContextProvider from '@/contexts/DeviceWidth/DeviceWidth.context';

const NunitoSans = localFont({
  src: [
    {
      path: '../public/assets/fonts/NunitoSans/NunitoSans_7pt_Condensed-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../public/assets/fonts/NunitoSans/NunitoSans_7pt_Condensed-SemiBold.ttf',
      weight: '600',
      style: 'semibold',
    },
  ],
  variable: '--font-NunitoSans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description:
    'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NunitoSans.variable}`}
      >
        <DeviceWidthContextProvider>
          <SidebarContextProvider>
            <Sidebar />
            <Header />

            {children}
          </SidebarContextProvider>
        </DeviceWidthContextProvider>
      </body>
    </html>
  );
}
